@php
    $isEdit = !empty($transaction);
    $selectedDirection = old('arah_transaksi', $transaction->arah_transaksi ?? 'Pemasukan');
    $selectedStatus = old('status_transaksi', $transaction->status_transaksi ?? 'Menunggu Verifikasi');
    $currentProof = $isEdit && $transaction->bukti_pembayaran ? basename($transaction->bukti_pembayaran) : null;
@endphp
<div class="modal-form-grid">
    <label class="form-group span-2"><span class="form-label">Berkas Nasabah</span><select class="form-select" name="id_berkas" required><option value="">Pilih berkas</option>@foreach($berkasList as $berkas)<option value="{{ $berkas->id }}" @selected(old('id_berkas', $transaction->id_berkas ?? '') == $berkas->id)>{{ $berkas->nasabah?->nama_nasabah }} · {{ $berkas->jenis_layanan }} ({{ $berkas->status_berkas }})</option>@endforeach</select></label>
    <label class="form-group"><span class="form-label">Arah Transaksi</span><select class="form-select" name="arah_transaksi" required>@foreach($transactionDirections as $direction)<option value="{{ $direction }}" @selected($selectedDirection === $direction)>{{ $direction }}</option>@endforeach</select></label>
    <label class="form-group"><span class="form-label">Kategori</span><select class="form-select" name="kategori" required>@foreach($categories as $category)<option value="{{ $category }}" @selected(old('kategori', $transaction->kategori ?? '') === $category)>{{ $category }}</option>@endforeach</select></label>
    <label class="form-group span-2"><span class="form-label">Nama Transaksi</span><input class="form-control" name="jenis_transaksi" value="{{ old('jenis_transaksi', $transaction->jenis_transaksi ?? '') }}" placeholder="Contoh: Biaya administrasi pengurusan berkas" required></label>
    <label class="form-group"><span class="form-label">Nominal</span><input class="form-control" type="number" min="1" step="0.01" name="nominal" value="{{ old('nominal', $transaction->nominal ?? '') }}" required></label>
    <label class="form-group"><span class="form-label">Tanggal</span><input class="form-control" type="date" name="tanggal_transaksi" value="{{ old('tanggal_transaksi', optional($transaction->tanggal_transaksi ?? null)->format('Y-m-d') ?? date('Y-m-d')) }}" required></label>
    <label class="form-group"><span class="form-label">Status</span><select class="form-select" name="status_transaksi" required>@foreach($paymentStatuses as $paymentStatus)<option value="{{ $paymentStatus }}" @selected($selectedStatus === $paymentStatus)>{{ $paymentStatus }}</option>@endforeach</select><small class="form-text">Pilih Menunggu Verifikasi saat data dan bukti sudah siap dicek Akuntan.</small></label>
    <label class="form-group"><span class="form-label">Metode Pembayaran</span><select class="form-select" name="metode_pembayaran" required>@foreach($paymentMethods as $method)<option value="{{ $method }}" @selected(old('metode_pembayaran', $transaction->metode_pembayaran ?? 'Tunai') === $method)>{{ $method }}</option>@endforeach</select></label>
    <label class="form-group span-2"><span class="form-label">Nomor Referensi</span><input class="form-control" name="nomor_referensi" value="{{ old('nomor_referensi', $transaction->nomor_referensi ?? '') }}" placeholder="Opsional, misalnya nomor transfer atau QRIS"></label>
    <div class="form-group span-2"><span class="form-label">Bukti Pembayaran <small class="text-muted">(opsional)</small></span><x-ui.upload-field name="bukti_pembayaran" :id="$isEdit ? 'bukti-pembayaran-'.$transaction->id : 'bukti-pembayaran-create'" accept=".jpg,.jpeg,.png,.pdf" help="JPG, PNG, atau PDF · maks. 2 MB" :current-file="$currentProof" :max-size="2097152" optional-note="Bukti membantu Akuntan memeriksa transaksi. Kosongkan saat edit bila file lama tetap dipakai." />@if($isEdit && $transaction->bukti_pembayaran)<a class="form-text" href="{{ route('dokumen.bukti.download', $transaction->id) }}">Unduh bukti tersimpan</a>@endif</div>
    <label class="form-group span-2"><span class="form-label">Keterangan</span><textarea class="form-control" name="keterangan" rows="3" placeholder="Catatan tambahan (opsional)">{{ old('keterangan', $transaction->keterangan ?? '') }}</textarea></label>
</div>
