@extends('layouts.app', ['pageTitle' => 'Dashboard'])
@section('content')
<div class="mb-8 flex flex-col gap-4 xl:flex-row xl:items-end xl:justify-between">
    <div><p class="text-sm font-semibold text-brand-600">Workspace Customer Service</p><h2 class="mt-1 text-3xl font-extrabold tracking-tight text-slate-900">Selamat datang, {{ auth()->user()->name }}.</h2><p class="mt-2 text-sm text-slate-400">Pantau pekerjaan yang membutuhkan tindakan hari ini dari satu tempat.</p></div>
    <div class="flex flex-wrap gap-3"><a href="{{ route('customers.create') }}" class="soft-button"><i data-lucide="user-plus" class="h-4 w-4 text-slate-400"></i> Tambah Nasabah</a><a href="{{ route('cases.create') }}" class="primary-pill"><i data-lucide="plus" class="h-4 w-4"></i> Input Berkas Baru</a></div>
</div>

<div class="mb-6 grid gap-6 md:grid-cols-3">
    <section class="app-card bank-tilt-card p-5"><div class="flex items-start justify-between"><div><p class="text-sm font-bold text-slate-600">Berkas aktif</p><p data-counter="{{ $counts['active'] + $counts['waitingDocuments'] }}" class="metric-value mt-3 text-3xl font-extrabold tracking-tight text-slate-900">{{ $counts['active'] + $counts['waitingDocuments'] }}</p></div><span class="rounded-lg bg-brand-100 p-2 text-brand-600"><i data-lucide="folder-open" class="h-5 w-5"></i></span></div><div class="mt-5 flex flex-wrap gap-2"><span class="rounded-md border border-slate-100 bg-slate-50 px-2 py-1 text-xs text-slate-500">{{ $counts['active'] }} diproses</span><span class="rounded-md border border-yellow-100 bg-yellow-50 px-2 py-1 text-xs text-yellow-700">{{ $counts['waitingDocuments'] }} dokumen kurang</span></div><p class="mt-4 text-xs text-slate-400">Kelola dokumen dan proses layanan tanpa input data berulang.</p></section>
    <section class="app-card bank-tilt-card p-5"><div class="flex items-start justify-between"><div><p class="text-sm font-bold text-slate-600">Status SLA</p><p data-counter="{{ $counts['nearSla'] + $counts['overdue'] }}" class="metric-value mt-3 text-3xl font-extrabold tracking-tight text-slate-900">{{ $counts['nearSla'] + $counts['overdue'] }}</p></div><span class="rounded-lg bg-red-50 p-2 text-red-500"><i data-lucide="alarm-clock" class="h-5 w-5"></i></span></div><div class="mt-5 flex flex-wrap gap-2"><span class="rounded-md border border-blue-100 bg-blue-50 px-2 py-1 text-xs text-blue-700">{{ $counts['nearSla'] }} mendekati</span><span class="rounded-md border border-red-100 bg-red-50 px-2 py-1 text-xs text-red-700">{{ $counts['overdue'] }} terlambat</span></div><p class="mt-4 text-xs text-slate-400">Prioritaskan berkas yang memiliki batas waktu paling dekat.</p></section>
    <section class="app-card bank-tilt-card p-5"><div class="flex items-start justify-between"><div><p class="text-sm font-bold text-slate-600">Transaksi diajukan</p><p data-counter="{{ $counts['pendingTransactions'] }}" class="metric-value mt-3 text-3xl font-extrabold tracking-tight text-slate-900">{{ $counts['pendingTransactions'] }}</p></div><span class="rounded-lg bg-emerald-50 p-2 text-emerald-600"><i data-lucide="badge-check" class="h-5 w-5"></i></span></div><div class="mt-5 inline-flex items-center gap-1 rounded-md border border-brand-100 bg-brand-50 px-2 py-1 text-xs font-semibold text-brand-700"><i data-lucide="shield-check" class="h-3.5 w-3.5"></i> Menunggu checker</div><p class="mt-4 text-xs text-slate-400">Transaksi akan diposting setelah disetujui oleh Admin.</p></section>
</div>

<div class="grid gap-6 xl:grid-cols-3">
    <div class="space-y-6 xl:col-span-2">
        <section class="app-card bank-tilt-card p-6"><div class="mb-6 flex flex-wrap items-center justify-between gap-4"><div><h3 class="text-lg font-extrabold text-slate-900">Ringkasan status berkas</h3><p class="mt-1 text-xs text-slate-400">Distribusi pekerjaan yang sedang menjadi tanggung jawab Anda.</p></div><span class="soft-button"><i data-lucide="activity" class="h-4 w-4 text-brand-600"></i> Hari ini</span></div><div class="h-[260px]"><canvas class="chart-reveal" id="csStatusChart"></canvas></div></section>
        <section class="table-shell"><div class="flex items-center justify-between border-b border-slate-100 px-6 py-5"><div><h3 class="font-extrabold text-slate-900">Berkas prioritas hari ini</h3><p class="mt-1 text-xs text-slate-400">Urut berdasarkan batas waktu SLA.</p></div><a href="{{ route('cases.index') }}" class="text-sm font-bold text-brand-600 hover:text-brand-700">Lihat semua</a></div><div class="overflow-x-auto"><table class="min-w-full text-sm"><thead class="bg-slate-50/70 text-left text-xs font-bold uppercase tracking-wide text-slate-400"><tr><th class="px-6 py-3">No. Berkas</th><th class="px-6 py-3">Nasabah</th><th class="px-6 py-3">Layanan</th><th class="px-6 py-3">SLA</th><th class="px-6 py-3 text-right">Aksi</th></tr></thead><tbody class="divide-y divide-slate-100">@forelse($priorityCases as $case)<tr class="transition hover:bg-brand-50/30"><td class="px-6 py-4 font-mono text-xs font-bold text-brand-700">{{ $case->file_number }}</td><td class="px-6 py-4"><p class="font-bold text-slate-800">{{ $case->customer->name }}</p><p class="mt-1 text-xs text-slate-400">{{ $case->customer->maskedAccountNumber() }}</p></td><td class="px-6 py-4 text-slate-600">{{ $case->serviceType->name }}</td><td class="px-6 py-4">@include('partials.sla-badge',['serviceCase'=>$case])</td><td class="px-6 py-4 text-right"><a href="{{ route('cases.show',$case) }}" class="text-sm font-bold text-brand-600 hover:text-brand-700">Buka</a></td></tr>@empty<tr><td colspan="5" class="px-6 py-10 text-center text-sm text-slate-400">Belum ada berkas aktif.</td></tr>@endforelse</tbody></table></div></section>
    </div>
    <div class="space-y-6"><section class="app-card bank-tilt-card p-6"><div class="mb-1 flex items-center justify-between"><h3 class="text-lg font-extrabold text-slate-900">Prioritas operasional</h3><i data-lucide="pie-chart" class="h-5 w-5 text-slate-300"></i></div><p class="text-xs leading-relaxed text-slate-400">Komposisi status berkas yang perlu Anda pantau.</p><div class="relative mt-5 h-[220px]"><canvas class="chart-reveal" id="csPriorityChart"></canvas><div class="pointer-events-none absolute inset-0 flex flex-col items-center justify-center"><span class="text-xs text-slate-400">Total tugas</span><span class="text-2xl font-extrabold text-slate-900">{{ $counts['active'] + $counts['waitingDocuments'] + $counts['nearSla'] + $counts['overdue'] }}</span></div></div><div class="mt-4 grid grid-cols-2 gap-y-3 text-xs"><span class="flex items-center gap-2 text-slate-500"><i class="h-2 w-2 rounded-full bg-brand-600"></i> Diproses</span><span class="flex items-center gap-2 text-slate-500"><i class="h-2 w-2 rounded-full bg-yellow-400"></i> Dokumen</span><span class="flex items-center gap-2 text-slate-500"><i class="h-2 w-2 rounded-full bg-blue-400"></i> Mendekati</span><span class="flex items-center gap-2 text-slate-500"><i class="h-2 w-2 rounded-full bg-red-500"></i> Terlambat</span></div></section>
        <section class="app-card bank-tilt-card overflow-hidden"><div class="border-b border-slate-100 px-6 py-5"><h3 class="font-extrabold text-slate-900">Transaksi terakhir</h3></div><div class="divide-y divide-slate-100">@forelse($recentTransactions as $transaction)<div class="p-5"><div class="flex items-start justify-between gap-3"><div><p class="text-sm font-bold text-slate-800">{{ $transaction->category }}</p><p class="mt-1 text-xs text-slate-400">{{ $transaction->transaction_number }} · {{ $transaction->serviceCase->file_number }}</p></div><p class="text-sm font-extrabold text-slate-900">Rp{{ number_format($transaction->amount,0,',','.') }}</p></div><div class="mt-3">@include('partials.transaction-badge',['transaction'=>$transaction])</div></div>@empty<div class="p-6 text-sm text-slate-400">Belum ada transaksi.</div>@endforelse</div></section></div>
</div>
@endsection

@push('scripts')
<script>
    document.addEventListener('DOMContentLoaded', () => {
        const chartText = '#94a3b8';
        new Chart(document.getElementById('csStatusChart'), { type: 'bar', data: { labels: ['Diproses','Dokumen Kurang','Mendekati SLA','Terlambat','Pending Verif.'], datasets: [{ label: 'Jumlah', data: [{{ $counts['active'] }},{{ $counts['waitingDocuments'] }},{{ $counts['nearSla'] }},{{ $counts['overdue'] }},{{ $counts['pendingTransactions'] }}], backgroundColor: ['#1f5f94','#f59e0b','#38bdf8','#ef4444','#2e79b5'], borderRadius: 10, borderSkipped: false, barThickness: 32 }] }, options: { responsive:true, maintainAspectRatio:false, plugins:{ legend:{display:false} }, scales:{ x:{grid:{display:false},border:{display:false},ticks:{color:chartText,font:{size:12}}}, y:{beginAtZero:true,grid:{color:'#f1f5f9'},border:{display:false},ticks:{precision:0,color:chartText}} } } });
        new Chart(document.getElementById('csPriorityChart'), { type: 'doughnut', data: { labels:['Diproses','Dokumen Kurang','Mendekati SLA','Terlambat'], datasets:[{ data:[{{ $counts['active'] }},{{ $counts['waitingDocuments'] }},{{ $counts['nearSla'] }},{{ $counts['overdue'] }}], backgroundColor:['#1f5f94','#f59e0b','#38bdf8','#ef4444'], borderColor:'#fff', borderWidth:4, borderRadius:5 }] }, options:{ responsive:true, maintainAspectRatio:false, cutout:'72%', plugins:{legend:{display:false}} } });
    });
</script>
@endpush
