@extends('layouts.app', ['pageTitle' => 'Data Nasabah'])
@section('content')
<div class="mb-6 flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between">
  <div><h1 class="text-2xl font-extrabold">Data Nasabah</h1><p class="mt-1 text-sm text-slate-500">Kelola data nasabah sesuai penugasan Customer Service.</p></div>
  @if(auth()->user()->isCustomerService())<a href="{{ route('customers.create') }}" class="primary-pill"><i data-lucide="user-plus" class="h-4 w-4"></i> Tambah Nasabah</a>@endif
</div>
<form class="mb-5 grid gap-3 md:grid-cols-[1fr_180px_auto]">
  <input name="q" value="{{ request('q') }}" class="form-input" placeholder="Cari nama, ID nasabah, atau telepon">
  <select name="status" class="form-input"><option value="">Semua Status</option><option value="aktif" @selected(request('status')==='aktif')>Aktif</option><option value="nonaktif" @selected(request('status')==='nonaktif')>Nonaktif</option></select>
  <button class="soft-button justify-center"><i data-lucide="search" class="h-4 w-4"></i> Cari</button>
</form>
<div class="table-shell overflow-x-auto"><table class="min-w-full text-sm"><thead class="bg-blue-50/70 text-left text-xs font-bold uppercase text-slate-500"><tr><th class="px-5 py-3">Nasabah</th><th class="px-5 py-3">Kontak</th><th class="px-5 py-3">CS</th><th class="px-5 py-3">Status</th><th class="px-5 py-3 text-right">Aksi</th></tr></thead><tbody class="divide-y divide-blue-50">@forelse($customers as $customer)<tr class="hover:bg-blue-50/30"><td class="px-5 py-4"><p class="font-semibold">{{ $customer->name }}</p><p class="font-mono text-xs text-slate-400">{{ $customer->customer_number }} · {{ $customer->maskedAccountNumber() }}</p></td><td class="px-5 py-4"><p>{{ $customer->phone ?: '-' }}</p><p class="text-xs text-slate-400">{{ $customer->email ?: '-' }}</p></td><td class="px-5 py-4">{{ $customer->assignedTo?->name ?? '-' }}</td><td class="px-5 py-4"><span class="status-chip {{ $customer->is_active ? 'bg-emerald-100 text-emerald-700' : 'bg-slate-200 text-slate-600' }}">{{ $customer->is_active ? 'Aktif' : 'Nonaktif' }}</span></td><td class="px-5 py-4 text-right"><a href="{{ route('customers.show',$customer) }}" class="mr-3 text-xs font-bold text-brand-700">Detail</a>@if(auth()->user()->isCustomerService() && $customer->assigned_to===auth()->id() && $customer->is_active)<a href="{{ route('customers.edit',$customer) }}" class="text-xs font-bold text-slate-600">Ubah</a>@elseif(auth()->user()->isAdmin())<form class="ml-3 inline" method="POST" action="{{ route('admin.customers.status',$customer) }}" onsubmit="return confirm('{{ $customer->is_active ? 'Nonaktifkan' : 'Aktifkan' }} nasabah ini?')">@csrf @method('PUT')<input type="hidden" name="is_active" value="{{ $customer->is_active ? 0 : 1 }}"><button class="text-xs font-bold {{ $customer->is_active ? 'text-red-600' : 'text-emerald-700' }}">{{ $customer->is_active ? 'Nonaktifkan' : 'Aktifkan' }}</button></form>@endif</td></tr>@empty<tr><td colspan="5" class="px-5 py-10 text-center text-slate-500">Belum ada data nasabah.</td></tr>@endforelse</tbody></table></div><div class="mt-5">{{ $customers->links() }}</div>
@endsection
