@extends('layouts.app', ['pageTitle' => 'Detail Nasabah'])
@section('content')
<div class="mb-6 flex flex-col gap-4 md:flex-row md:items-start md:justify-between"><div><p class="font-mono text-xs font-bold text-brand-700">{{ $customer->customer_number }}</p><h1 class="text-2xl font-extrabold">{{ $customer->name }}</h1><p class="mt-1 text-sm text-slate-500">CS Penanggung Jawab: {{ $customer->assignedTo?->name ?? '-' }}</p></div><div class="flex gap-2">@if(auth()->user()->isCustomerService() && $customer->assigned_to===auth()->id() && $customer->is_active)<a href="{{ route('customers.edit',$customer) }}" class="soft-button"><i data-lucide="pencil" class="h-4 w-4"></i> Ubah</a><a href="{{ route('cases.create',['customer'=>$customer->id]) }}" class="primary-pill"><i data-lucide="folder-plus" class="h-4 w-4"></i> Buat Berkas</a>@endif</div></div>
<div class="grid gap-6 lg:grid-cols-3">
  <section class="app-card p-6"><h2 class="font-bold">Profil Nasabah</h2><dl class="mt-4 space-y-4 text-sm"><div><dt class="text-slate-500">NIK</dt><dd class="mt-1 font-semibold">{{ $customer->maskedNik() }}</dd></div><div><dt class="text-slate-500">Nomor Rekening</dt><dd class="mt-1 font-semibold">{{ $customer->maskedAccountNumber() }}</dd></div><div><dt class="text-slate-500">Kontak</dt><dd class="mt-1 font-semibold">{{ $customer->phone ?: '-' }}</dd><dd class="text-xs text-slate-400">{{ $customer->email ?: '-' }}</dd></div><div><dt class="text-slate-500">Status</dt><dd class="mt-1"><span class="status-chip {{ $customer->is_active?'bg-emerald-100 text-emerald-700':'bg-slate-200 text-slate-600' }}">{{ $customer->is_active?'Aktif':'Nonaktif' }}</span></dd></div></dl></section>
  <section class="table-shell lg:col-span-2"><div class="border-b border-blue-100 p-5"><h2 class="font-bold">Riwayat Berkas</h2><p class="mt-1 text-xs text-slate-400">Pilih berkas untuk mengelola dokumen, SLA, dan transaksi.</p></div><div class="divide-y divide-blue-50">@forelse($customer->serviceCases as $case)<a class="block p-5 transition hover:bg-blue-50/30" href="{{ route('cases.show',$case) }}"><div class="flex items-start justify-between gap-3"><div><p class="font-mono text-xs font-bold text-brand-700">{{ $case->file_number }}</p><p class="mt-1 text-sm font-semibold">{{ $case->serviceType->name }}</p></div>@include('partials.sla-badge',['serviceCase'=>$case])</div></a>@empty<div class="p-6 text-sm text-slate-500">Belum ada berkas. Buat berkas pertama dari tombol di atas.</div>@endforelse</div></section>
</div>
<section class="table-shell mt-6"><div class="border-b border-blue-100 p-5"><h2 class="font-bold">Riwayat Transaksi Administrasi</h2><p class="mt-1 text-xs text-slate-400">Transaksi selalu terhubung dengan berkas layanan dan proses maker–checker.</p></div><div class="overflow-x-auto"><table class="min-w-full text-sm"><thead class="bg-blue-50/60 text-left text-xs font-bold uppercase text-slate-500"><tr><th class="px-5 py-3">No. Transaksi</th><th class="px-5 py-3">Berkas</th><th class="px-5 py-3">Kategori</th><th class="px-5 py-3">Nominal</th><th class="px-5 py-3">Status</th></tr></thead><tbody class="divide-y divide-blue-50">@forelse($customer->transactions as $transaction)<tr><td class="px-5 py-3 font-mono text-xs font-bold text-brand-700"><a href="{{ route('transactions.show',$transaction) }}" class="hover:underline">{{ $transaction->transaction_number }}</a></td><td class="px-5 py-3 font-mono text-xs">{{ $transaction->serviceCase?->file_number ?? '-' }}</td><td class="px-5 py-3">{{ $transaction->category }}</td><td class="px-5 py-3 font-semibold">Rp{{ number_format($transaction->amount,0,',','.') }}</td><td class="px-5 py-3">@include('partials.transaction-badge',['transaction'=>$transaction])</td></tr>@empty<tr><td colspan="5" class="px-5 py-8 text-center text-slate-500">Belum ada transaksi terkait nasabah ini.</td></tr>@endforelse</tbody></table></div></section>
@endsection
