-- Bank X Customer Service Administration System
-- Full schema + demo data for phpMyAdmin import
-- Import this file once. After import, do NOT run "php artisan migrate".
-- To reset through Laravel later, run: php artisan migrate:fresh --seed

CREATE DATABASE IF NOT EXISTS `bank_ta` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE `bank_ta`;
SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS=0;
DROP TABLE IF EXISTS `transaction_correction_requests`;
DROP TABLE IF EXISTS `sla_notifications`;
DROP TABLE IF EXISTS `export_logs`;
DROP TABLE IF EXISTS `audit_logs`;
DROP TABLE IF EXISTS `daily_reconciliations`;
DROP TABLE IF EXISTS `journal_entries`;
DROP TABLE IF EXISTS `administrative_transactions`;
DROP TABLE IF EXISTS `case_documents`;
DROP TABLE IF EXISTS `service_cases`;
DROP TABLE IF EXISTS `service_types`;
DROP TABLE IF EXISTS `customers`;
DROP TABLE IF EXISTS `sessions`;
DROP TABLE IF EXISTS `password_reset_tokens`;
DROP TABLE IF EXISTS `users`;
DROP TABLE IF EXISTS `cache_locks`;
DROP TABLE IF EXISTS `cache`;
DROP TABLE IF EXISTS `job_batches`;
DROP TABLE IF EXISTS `failed_jobs`;
DROP TABLE IF EXISTS `jobs`;
DROP TABLE IF EXISTS `migrations`;
SET FOREIGN_KEY_CHECKS=1;

CREATE TABLE `migrations` (`id` int unsigned NOT NULL AUTO_INCREMENT, `migration` varchar(255) NOT NULL, `batch` int NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `users` (
 `id` bigint unsigned NOT NULL AUTO_INCREMENT, `employee_id` varchar(255) NOT NULL, `name` varchar(255) NOT NULL, `email` varchar(255) NOT NULL, `role` enum('cs','admin') NOT NULL DEFAULT 'cs', `is_active` tinyint(1) NOT NULL DEFAULT 1, `last_login_at` timestamp NULL DEFAULT NULL, `email_verified_at` timestamp NULL DEFAULT NULL, `password` varchar(255) NOT NULL, `remember_token` varchar(100) DEFAULT NULL, `created_at` timestamp NULL DEFAULT NULL, `updated_at` timestamp NULL DEFAULT NULL,
 PRIMARY KEY (`id`), UNIQUE KEY `users_employee_id_unique` (`employee_id`), UNIQUE KEY `users_email_unique` (`email`), KEY `users_role_index` (`role`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `password_reset_tokens` (`email` varchar(255) NOT NULL,`token` varchar(255) NOT NULL,`created_at` timestamp NULL DEFAULT NULL,PRIMARY KEY (`email`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `sessions` (`id` varchar(255) NOT NULL,`user_id` bigint unsigned DEFAULT NULL,`ip_address` varchar(45) DEFAULT NULL,`user_agent` text,`payload` longtext NOT NULL,`last_activity` int NOT NULL,PRIMARY KEY (`id`),KEY `sessions_user_id_index` (`user_id`),KEY `sessions_last_activity_index` (`last_activity`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `cache` (`key` varchar(255) NOT NULL,`value` mediumtext NOT NULL,`expiration` int NOT NULL,PRIMARY KEY (`key`),KEY `cache_expiration_index` (`expiration`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `cache_locks` (`key` varchar(255) NOT NULL,`owner` varchar(255) NOT NULL,`expiration` int NOT NULL,PRIMARY KEY (`key`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `jobs` (`id` bigint unsigned NOT NULL AUTO_INCREMENT,`queue` varchar(255) NOT NULL,`payload` longtext NOT NULL,`attempts` tinyint unsigned NOT NULL,`reserved_at` int unsigned DEFAULT NULL,`available_at` int unsigned NOT NULL,`created_at` int unsigned NOT NULL,PRIMARY KEY (`id`),KEY `jobs_queue_index` (`queue`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `job_batches` (`id` varchar(255) NOT NULL,`name` varchar(255) NOT NULL,`total_jobs` int NOT NULL,`pending_jobs` int NOT NULL,`failed_jobs` int NOT NULL,`failed_job_ids` longtext NOT NULL,`options` mediumtext,`cancelled_at` int DEFAULT NULL,`created_at` int NOT NULL,`finished_at` int DEFAULT NULL,PRIMARY KEY (`id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `failed_jobs` (`id` bigint unsigned NOT NULL AUTO_INCREMENT,`uuid` varchar(255) NOT NULL,`connection` text NOT NULL,`queue` text NOT NULL,`payload` longtext NOT NULL,`exception` longtext NOT NULL,`failed_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY (`id`),UNIQUE KEY `failed_jobs_uuid_unique` (`uuid`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `customers` (`id` bigint unsigned NOT NULL AUTO_INCREMENT,`customer_number` varchar(255) NOT NULL,`name` varchar(255) NOT NULL,`nik_encrypted` varchar(255) DEFAULT NULL,`account_number_encrypted` varchar(255) DEFAULT NULL,`phone` varchar(255) DEFAULT NULL,`email` varchar(255) DEFAULT NULL,`assigned_to` bigint unsigned DEFAULT NULL,`is_active` tinyint(1) NOT NULL DEFAULT 1,`created_at` timestamp NULL DEFAULT NULL,`updated_at` timestamp NULL DEFAULT NULL,PRIMARY KEY (`id`),UNIQUE KEY `customers_customer_number_unique` (`customer_number`),KEY `customers_assigned_to_foreign` (`assigned_to`),CONSTRAINT `customers_assigned_to_foreign` FOREIGN KEY (`assigned_to`) REFERENCES `users` (`id`) ON DELETE SET NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `service_types` (`id` bigint unsigned NOT NULL AUTO_INCREMENT,`name` varchar(255) NOT NULL,`sla_hours` int unsigned NOT NULL DEFAULT 24,`required_documents` json DEFAULT NULL,`is_active` tinyint(1) NOT NULL DEFAULT 1,`created_at` timestamp NULL DEFAULT NULL,`updated_at` timestamp NULL DEFAULT NULL,PRIMARY KEY (`id`),UNIQUE KEY `service_types_name_unique` (`name`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `service_cases` (`id` bigint unsigned NOT NULL AUTO_INCREMENT,`file_number` varchar(255) NOT NULL,`customer_id` bigint unsigned NOT NULL,`service_type_id` bigint unsigned NOT NULL,`assigned_to` bigint unsigned NOT NULL,`created_by` bigint unsigned NOT NULL,`status` enum('baru','menunggu_dokumen','diproses','selesai','ditolak') NOT NULL DEFAULT 'baru',`sla_status` enum('aman','mendekati','terlambat','selesai') NOT NULL DEFAULT 'aman',`received_at` timestamp NOT NULL,`due_at` timestamp NOT NULL,`completed_at` timestamp NULL DEFAULT NULL,`notes` text DEFAULT NULL,`created_at` timestamp NULL DEFAULT NULL,`updated_at` timestamp NULL DEFAULT NULL,PRIMARY KEY (`id`),UNIQUE KEY `service_cases_file_number_unique` (`file_number`),KEY `service_cases_status_index` (`status`),KEY `service_cases_sla_status_index` (`sla_status`),KEY `service_cases_due_at_index` (`due_at`),CONSTRAINT `service_cases_customer_id_foreign` FOREIGN KEY (`customer_id`) REFERENCES `customers` (`id`) ON DELETE RESTRICT,CONSTRAINT `service_cases_service_type_id_foreign` FOREIGN KEY (`service_type_id`) REFERENCES `service_types` (`id`) ON DELETE RESTRICT,CONSTRAINT `service_cases_assigned_to_foreign` FOREIGN KEY (`assigned_to`) REFERENCES `users` (`id`) ON DELETE RESTRICT,CONSTRAINT `service_cases_created_by_foreign` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE RESTRICT) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `case_documents` (`id` bigint unsigned NOT NULL AUTO_INCREMENT,`service_case_id` bigint unsigned NOT NULL,`document_type` varchar(255) NOT NULL,`original_name` varchar(255) NOT NULL,`storage_path` varchar(255) NOT NULL,`mime_type` varchar(150) NOT NULL,`size_bytes` bigint unsigned NOT NULL,`uploaded_by` bigint unsigned NOT NULL,`retention_until` timestamp NULL DEFAULT NULL,`created_at` timestamp NULL DEFAULT NULL,`updated_at` timestamp NULL DEFAULT NULL,PRIMARY KEY (`id`),CONSTRAINT `case_documents_service_case_id_foreign` FOREIGN KEY (`service_case_id`) REFERENCES `service_cases` (`id`) ON DELETE CASCADE,CONSTRAINT `case_documents_uploaded_by_foreign` FOREIGN KEY (`uploaded_by`) REFERENCES `users` (`id`) ON DELETE RESTRICT) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `administrative_transactions` (`id` bigint unsigned NOT NULL AUTO_INCREMENT,`transaction_number` varchar(255) NOT NULL,`service_case_id` bigint unsigned NOT NULL,`customer_id` bigint unsigned NOT NULL,`created_by` bigint unsigned NOT NULL,`verified_by` bigint unsigned DEFAULT NULL,`corrected_from_id` bigint unsigned DEFAULT NULL,`category` varchar(255) NOT NULL,`payment_method` varchar(255) NOT NULL,`amount` decimal(18,2) NOT NULL,`debit_account` varchar(255) NOT NULL DEFAULT '101.00.00 Kas (Teller)',`credit_account` varchar(255) NOT NULL DEFAULT '401.05.00 Pendapatan Biaya Administrasi',`description` text DEFAULT NULL,`proof_path` varchar(255) DEFAULT NULL,`status` enum('draft','menunggu_verifikasi','disetujui','dikembalikan','ditolak','dibatalkan','dikoreksi') NOT NULL DEFAULT 'draft',`submitted_at` timestamp NULL DEFAULT NULL,`verified_at` timestamp NULL DEFAULT NULL,`verification_note` text DEFAULT NULL,`cancelled_at` timestamp NULL DEFAULT NULL,`created_at` timestamp NULL DEFAULT NULL,`updated_at` timestamp NULL DEFAULT NULL,PRIMARY KEY (`id`),UNIQUE KEY `administrative_transactions_transaction_number_unique` (`transaction_number`),KEY `administrative_transactions_status_index` (`status`),CONSTRAINT `administrative_transactions_service_case_id_foreign` FOREIGN KEY (`service_case_id`) REFERENCES `service_cases` (`id`) ON DELETE RESTRICT,CONSTRAINT `administrative_transactions_customer_id_foreign` FOREIGN KEY (`customer_id`) REFERENCES `customers` (`id`) ON DELETE RESTRICT,CONSTRAINT `administrative_transactions_created_by_foreign` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE RESTRICT,CONSTRAINT `administrative_transactions_verified_by_foreign` FOREIGN KEY (`verified_by`) REFERENCES `users` (`id`) ON DELETE SET NULL,CONSTRAINT `administrative_transactions_corrected_from_id_foreign` FOREIGN KEY (`corrected_from_id`) REFERENCES `administrative_transactions` (`id`) ON DELETE SET NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `journal_entries` (`id` bigint unsigned NOT NULL AUTO_INCREMENT,`journal_number` varchar(255) NOT NULL,`administrative_transaction_id` bigint unsigned NOT NULL,`debit_account` varchar(255) NOT NULL,`credit_account` varchar(255) NOT NULL,`amount` decimal(18,2) NOT NULL,`entry_type` enum('normal','reversal') NOT NULL DEFAULT 'normal',`posted_by` bigint unsigned NOT NULL,`posted_at` timestamp NOT NULL,`created_at` timestamp NULL DEFAULT NULL,`updated_at` timestamp NULL DEFAULT NULL,PRIMARY KEY (`id`),UNIQUE KEY `journal_entries_journal_number_unique` (`journal_number`),CONSTRAINT `journal_entries_administrative_transaction_id_foreign` FOREIGN KEY (`administrative_transaction_id`) REFERENCES `administrative_transactions` (`id`) ON DELETE CASCADE,CONSTRAINT `journal_entries_posted_by_foreign` FOREIGN KEY (`posted_by`) REFERENCES `users` (`id`) ON DELETE RESTRICT) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `daily_reconciliations` (`id` bigint unsigned NOT NULL AUTO_INCREMENT,`reconciliation_date` date NOT NULL,`system_total` decimal(18,2) NOT NULL,`physical_total` decimal(18,2) NOT NULL,`difference` decimal(18,2) NOT NULL,`status` enum('sesuai','selisih_lebih','selisih_kurang','perlu_tindak_lanjut') NOT NULL,`note` text DEFAULT NULL,`created_by` bigint unsigned NOT NULL,`created_at` timestamp NULL DEFAULT NULL,`updated_at` timestamp NULL DEFAULT NULL,PRIMARY KEY (`id`),UNIQUE KEY `daily_reconciliations_reconciliation_date_unique` (`reconciliation_date`),CONSTRAINT `daily_reconciliations_created_by_foreign` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE RESTRICT) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `audit_logs` (`id` bigint unsigned NOT NULL AUTO_INCREMENT,`user_id` bigint unsigned DEFAULT NULL,`role` varchar(255) DEFAULT NULL,`module` varchar(255) NOT NULL,`action` varchar(255) NOT NULL,`subject_type` varchar(255) NOT NULL,`subject_id` bigint unsigned DEFAULT NULL,`before_values` json DEFAULT NULL,`after_values` json DEFAULT NULL,`ip_address` varchar(45) DEFAULT NULL,`user_agent` text DEFAULT NULL,`description` text DEFAULT NULL,`created_at` timestamp NULL DEFAULT NULL,`updated_at` timestamp NULL DEFAULT NULL,PRIMARY KEY (`id`),KEY `audit_logs_module_action_index` (`module`,`action`),KEY `audit_logs_subject_type_subject_id_index` (`subject_type`,`subject_id`),CONSTRAINT `audit_logs_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `export_logs` (`id` bigint unsigned NOT NULL AUTO_INCREMENT,`user_id` bigint unsigned NOT NULL,`report_type` varchar(255) NOT NULL,`format` varchar(255) NOT NULL,`ip_address` varchar(45) DEFAULT NULL,`user_agent` text DEFAULT NULL,`created_at` timestamp NULL DEFAULT NULL,`updated_at` timestamp NULL DEFAULT NULL,PRIMARY KEY (`id`),CONSTRAINT `export_logs_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `sla_notifications` (`id` bigint unsigned NOT NULL AUTO_INCREMENT,`service_case_id` bigint unsigned NOT NULL,`recipient_id` bigint unsigned NOT NULL,`sla_status` enum('mendekati','terlambat') NOT NULL,`title` varchar(255) NOT NULL,`message` text NOT NULL,`read_at` timestamp NULL DEFAULT NULL,`created_at` timestamp NULL DEFAULT NULL,`updated_at` timestamp NULL DEFAULT NULL,PRIMARY KEY (`id`),UNIQUE KEY `sla_notification_unique_status` (`service_case_id`,`recipient_id`,`sla_status`),KEY `sla_notifications_recipient_id_read_at_index` (`recipient_id`,`read_at`),CONSTRAINT `sla_notifications_service_case_id_foreign` FOREIGN KEY (`service_case_id`) REFERENCES `service_cases` (`id`) ON DELETE CASCADE,CONSTRAINT `sla_notifications_recipient_id_foreign` FOREIGN KEY (`recipient_id`) REFERENCES `users` (`id`) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `transaction_correction_requests` (`id` bigint unsigned NOT NULL AUTO_INCREMENT,`administrative_transaction_id` bigint unsigned NOT NULL,`requested_by` bigint unsigned NOT NULL,`reviewed_by` bigint unsigned DEFAULT NULL,`replacement_transaction_id` bigint unsigned DEFAULT NULL,`proposed_category` varchar(255) NOT NULL,`proposed_payment_method` varchar(255) NOT NULL,`proposed_amount` decimal(18,2) NOT NULL,`proposed_description` text DEFAULT NULL,`reason` text NOT NULL,`supporting_path` varchar(255) DEFAULT NULL,`status` enum('menunggu_verifikasi','disetujui','ditolak') NOT NULL DEFAULT 'menunggu_verifikasi',`reviewed_at` timestamp NULL DEFAULT NULL,`review_note` text DEFAULT NULL,`created_at` timestamp NULL DEFAULT NULL,`updated_at` timestamp NULL DEFAULT NULL,PRIMARY KEY (`id`),KEY `tcr_status_idx` (`status`),KEY `tcr_tx_status_idx` (`administrative_transaction_id`,`status`),CONSTRAINT `tcr_admin_tx_fk` FOREIGN KEY (`administrative_transaction_id`) REFERENCES `administrative_transactions` (`id`) ON DELETE RESTRICT,CONSTRAINT `tcr_requested_by_fk` FOREIGN KEY (`requested_by`) REFERENCES `users` (`id`) ON DELETE RESTRICT,CONSTRAINT `tcr_reviewed_by_fk` FOREIGN KEY (`reviewed_by`) REFERENCES `users` (`id`) ON DELETE SET NULL,CONSTRAINT `tcr_replacement_tx_fk` FOREIGN KEY (`replacement_transaction_id`) REFERENCES `administrative_transactions` (`id`) ON DELETE SET NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `users` (`id`,`employee_id`,`name`,`email`,`role`,`is_active`,`password`,`created_at`,`updated_at`) VALUES
(1,'ADM-001','Budi Admin','admin@bankx.test','admin',1,'$2y$12$EEvH1zxUE2RzVPkowUkNWOsXSp0GHPdMQEU7SNtOEpDn9kF4oYzpq','2026-07-03 08:00:00','2026-07-03 08:00:00'),
(2,'CS-001','Rina S.','rina@bankx.test','cs',1,'$2y$12$EEvH1zxUE2RzVPkowUkNWOsXSp0GHPdMQEU7SNtOEpDn9kF4oYzpq','2026-07-03 08:00:00','2026-07-03 08:00:00');
INSERT INTO `service_types` (`id`,`name`,`sla_hours`,`required_documents`,`is_active`,`created_at`,`updated_at`) VALUES
(1,'Pembukaan Rekening Giro',24,'["Formulir Pembukaan Rekening","Akta Pendirian Perusahaan","KTP Penanggung Jawab"]',1,'2026-07-03 08:00:00','2026-07-03 08:00:00'),
(2,'Penggantian Kartu',4,'["Formulir Penggantian Kartu","Identitas Nasabah"]',1,'2026-07-03 08:00:00','2026-07-03 08:00:00'),
(3,'Cetak Rekening Koran',2,'["Formulir Permintaan","Identitas Nasabah"]',1,'2026-07-03 08:00:00','2026-07-03 08:00:00');
-- Sensitive fields are intentionally NULL in SQL demo imports: direct imports do not know your Laravel APP_KEY.
INSERT INTO `customers` (`id`,`customer_number`,`name`,`nik_encrypted`,`account_number_encrypted`,`phone`,`email`,`assigned_to`,`is_active`,`created_at`,`updated_at`) VALUES
(1,'NSB-202607-0001','PT. Maju Bersama',NULL,NULL,'081234567890','admin@maju-bersama.test',2,1,'2026-07-03 08:00:00','2026-07-03 08:00:00');
INSERT INTO `service_cases` (`id`,`file_number`,`customer_id`,`service_type_id`,`assigned_to`,`created_by`,`status`,`sla_status`,`received_at`,`due_at`,`notes`,`created_at`,`updated_at`) VALUES
(1,'BRK-202607-0001',1,1,2,2,'diproses','mendekati','2026-07-03 08:00:00','2026-07-04 08:00:00','Permohonan pembukaan rekening giro untuk payroll.','2026-07-03 08:00:00','2026-07-03 08:00:00');
INSERT INTO `administrative_transactions` (`id`,`transaction_number`,`service_case_id`,`customer_id`,`created_by`,`verified_by`,`category`,`payment_method`,`amount`,`debit_account`,`credit_account`,`description`,`status`,`submitted_at`,`verified_at`,`verification_note`,`created_at`,`updated_at`) VALUES
(1,'TRX-202607-0001',1,1,2,NULL,'Biaya Materai','Setoran Tunai',10000.00,'101.00.00 Kas (Teller)','401.05.00 Pendapatan Biaya Administrasi','Biaya materai pembukaan rekening giro.','menunggu_verifikasi','2026-07-03 09:00:00',NULL,NULL,'2026-07-03 09:00:00','2026-07-03 09:00:00'),
(2,'TRX-202607-0002',1,1,2,1,'Biaya Administrasi Layanan','Potong Saldo Rekening (Auto-debit)',50000.00,'101.00.00 Kas (Teller)','401.05.00 Pendapatan Biaya Administrasi','Biaya administrasi pembukaan rekening giro.','disetujui','2026-07-02 10:00:00','2026-07-02 10:20:00','Data dan nominal sesuai.','2026-07-02 10:00:00','2026-07-02 10:20:00');
INSERT INTO `journal_entries` (`id`,`journal_number`,`administrative_transaction_id`,`debit_account`,`credit_account`,`amount`,`entry_type`,`posted_by`,`posted_at`,`created_at`,`updated_at`) VALUES
(1,'JRN-202607-0001',2,'101.00.00 Kas (Teller)','401.05.00 Pendapatan Biaya Administrasi',50000.00,'normal',1,'2026-07-02 10:20:00','2026-07-02 10:20:00','2026-07-02 10:20:00');
INSERT INTO `audit_logs` (`id`,`user_id`,`role`,`module`,`action`,`subject_type`,`subject_id`,`after_values`,`ip_address`,`user_agent`,`description`,`created_at`,`updated_at`) VALUES
(1,2,'cs','service_case','create','App\Models\ServiceCase',1,'{"file_number":"BRK-202607-0001","status":"diproses"}','127.0.0.1','SQL demo import','Berkas layanan dibuat oleh Maker.','2026-07-03 08:00:00','2026-07-03 08:00:00'),
(2,1,'admin','transaction','approve','App\Models\AdministrativeTransaction',2,'{"status":"disetujui"}','127.0.0.1','SQL demo import','Checker menyetujui transaksi dan jurnal terbentuk.','2026-07-02 10:20:00','2026-07-02 10:20:00');
INSERT INTO `migrations` (`migration`,`batch`) VALUES
('0001_01_01_000000_create_users_table',1),('0001_01_01_000001_create_cache_table',1),('0001_01_01_000002_create_jobs_table',1),('2026_07_03_000100_create_customers_table',1),('2026_07_03_000110_create_service_types_table',1),('2026_07_03_000120_create_service_cases_table',1),('2026_07_03_000130_create_case_documents_table',1),('2026_07_03_000140_create_administrative_transactions_table',1),('2026_07_03_000150_create_journal_entries_table',1),('2026_07_03_000160_create_daily_reconciliations_table',1),('2026_07_03_000170_create_audit_logs_table',1),('2026_07_03_000180_create_export_logs_table',1),('2026_07_03_000190_create_sla_notifications_table',1),('2026_07_03_000200_create_transaction_correction_requests_table',1);
